/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardealership;

import java.io.File;
import javax.swing.JOptionPane;
import java.io.PrintWriter;
import java.io.IOException;
import javax.swing.JFileChooser;


/**
 *
 * @author rjnkr
 */
public class finance extends javax.swing.JFrame {

    /**
     * Creates new form finance
     */
    public finance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPersonalInfo = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblCell = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblOccupation = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtCell = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txtOccupation = new javax.swing.JTextField();
        lblHome = new javax.swing.JLabel();
        lblWork = new javax.swing.JLabel();
        lblGross = new javax.swing.JLabel();
        lblNet = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblVehicle = new javax.swing.JLabel();
        txtHome = new javax.swing.JTextField();
        txtWork = new javax.swing.JTextField();
        txtGross = new javax.swing.JTextField();
        txtNet = new javax.swing.JTextField();
        cmbVehicle = new javax.swing.JComboBox<>();
        rbtnYes = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        pnlNextOfKin = new javax.swing.JPanel();
        lblNextFirstName = new javax.swing.JLabel();
        lblNextSurname = new javax.swing.JLabel();
        lblNextCell = new javax.swing.JLabel();
        lblNextRelationship = new javax.swing.JLabel();
        txtNextFirstName = new javax.swing.JTextField();
        txtNextSurname = new javax.swing.JTextField();
        txtNextRelationship = new javax.swing.JTextField();
        txtNextCell = new javax.swing.JTextField();
        pnlAttachements = new javax.swing.JPanel();
        lblAttachmentID = new javax.swing.JLabel();
        lblAttachmentPayslip = new javax.swing.JLabel();
        lblAttachmentLicense = new javax.swing.JLabel();
        txtAttachmentPayslip = new javax.swing.JTextField();
        txtAttachmentID = new javax.swing.JTextField();
        txtAttachmentLicense = new javax.swing.JTextField();
        btnIDBrowse = new javax.swing.JButton();
        btnPayslipBrowse = new javax.swing.JButton();
        btnLicneseBrowse = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPersonalInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Information"));

        lblFirstName.setText("First Name");

        lblSurname.setText("Surname");

        lblCell.setText("Cell no");

        lblID.setText("ID no");

        lblGender.setText("Gender");

        lblOccupation.setText("Occupation");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        lblHome.setText("Home address");

        lblWork.setText("Work address");

        lblGross.setText("Gross Pay");

        lblNet.setText("Net Pay");

        lblLicense.setText("Valid license");

        lblVehicle.setText("Vehicle");

        cmbVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polo Vivo", "Polo", "Tcross", "Troc" }));

        rbtnYes.setText("Yes");

        rbtnNo.setText("No");

        javax.swing.GroupLayout pnlPersonalInfoLayout = new javax.swing.GroupLayout(pnlPersonalInfo);
        pnlPersonalInfo.setLayout(pnlPersonalInfoLayout);
        pnlPersonalInfoLayout.setHorizontalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(lblSurname)
                    .addComponent(lblCell)
                    .addComponent(lblID)
                    .addComponent(lblGender)
                    .addComponent(lblOccupation))
                .addGap(26, 26, 26)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHome))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblWork))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(txtCell, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGross))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNet))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblVehicle))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(lblLicense)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtWork, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGross, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbVehicle, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                            .addComponent(rbtnYes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbtnNo)))
                    .addComponent(txtNet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHome, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPersonalInfoLayout.setVerticalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHome)
                    .addComponent(txtHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWork)
                    .addComponent(txtWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCell)
                    .addComponent(txtCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGross)
                    .addComponent(txtGross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNet)
                    .addComponent(txtNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicense)
                    .addComponent(rbtnYes)
                    .addComponent(rbtnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOccupation)
                    .addComponent(lblVehicle)
                    .addComponent(cmbVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlNextOfKin.setBorder(javax.swing.BorderFactory.createTitledBorder("Next of kin"));

        lblNextFirstName.setText("First Name");

        lblNextSurname.setText("Surname");

        lblNextCell.setText("Cell no");

        lblNextRelationship.setText("Relationship");

        javax.swing.GroupLayout pnlNextOfKinLayout = new javax.swing.GroupLayout(pnlNextOfKin);
        pnlNextOfKin.setLayout(pnlNextOfKinLayout);
        pnlNextOfKinLayout.setHorizontalGroup(
            pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextOfKinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNextOfKinLayout.createSequentialGroup()
                        .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNextSurname)
                            .addComponent(lblNextFirstName))
                        .addGap(26, 26, 26)
                        .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNextSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtNextFirstName)))
                    .addGroup(pnlNextOfKinLayout.createSequentialGroup()
                        .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNextCell)
                            .addComponent(lblNextRelationship))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNextRelationship)
                            .addComponent(txtNextCell))))
                .addContainerGap())
        );
        pnlNextOfKinLayout.setVerticalGroup(
            pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextOfKinLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNextFirstName)
                    .addComponent(txtNextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNextSurname)
                    .addComponent(txtNextSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNextCell)
                    .addComponent(txtNextCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNextOfKinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNextRelationship)
                    .addComponent(txtNextRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAttachements.setBorder(javax.swing.BorderFactory.createTitledBorder("Attachements"));

        lblAttachmentID.setText("ID");

        lblAttachmentPayslip.setText("Latest payslip");

        lblAttachmentLicense.setText("License");

        btnIDBrowse.setText("Browse");
        btnIDBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDBrowseActionPerformed(evt);
            }
        });

        btnPayslipBrowse.setText("Browse");
        btnPayslipBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayslipBrowseActionPerformed(evt);
            }
        });

        btnLicneseBrowse.setText("Browse");
        btnLicneseBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicneseBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAttachementsLayout = new javax.swing.GroupLayout(pnlAttachements);
        pnlAttachements.setLayout(pnlAttachementsLayout);
        pnlAttachementsLayout.setHorizontalGroup(
            pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttachementsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAttachmentPayslip)
                    .addComponent(lblAttachmentID)
                    .addComponent(lblAttachmentLicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAttachmentPayslip, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txtAttachmentID)
                    .addComponent(txtAttachmentLicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIDBrowse)
                    .addComponent(btnPayslipBrowse)
                    .addComponent(btnLicneseBrowse))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlAttachementsLayout.setVerticalGroup(
            pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttachementsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttachmentID)
                    .addComponent(txtAttachmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIDBrowse))
                .addGap(23, 23, 23)
                .addGroup(pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttachmentPayslip)
                    .addComponent(txtAttachmentPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayslipBrowse))
                .addGap(23, 23, 23)
                .addGroup(pnlAttachementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttachmentLicense)
                    .addComponent(txtAttachmentLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLicneseBrowse))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit Application");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlNextOfKin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlAttachements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNextOfKin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAttachements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSubmit))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new welcomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (rbtnYes.isSelected()) {

            //saving to file
            try {
                PrintWriter myWriter = new PrintWriter(txtFirstName.getText() + " " + txtSurname.getText() + ".txt");
                myWriter.println("Personal Information.");
                myWriter.println("---------------------------------------------------------------------");
                myWriter.println("Fullnames: " + txtFirstName.getText() + " " + txtSurname.getText());
                myWriter.println("ID Number: " + txtID.getText());
                myWriter.println("Cell Number: " + txtCell.getText());
                myWriter.println("Gender: " + cmbGender.getSelectedItem());
                myWriter.println("Ocuupation: " + txtOccupation.getText());
                myWriter.println("Home Address: " + txtHome.getText());
                myWriter.println("Work Address: " + txtWork.getText());
                myWriter.println("Gross Pay: " + txtGross.getText());
                myWriter.println("Net Pay: " + txtNet.getText());
                myWriter.println("Valid Licese: " + "Yes");
                myWriter.println("Model: " + cmbVehicle.getSelectedItem());

                myWriter.println("\nNext of kin Information.");
                myWriter.println("---------------------------------------------------------------------");
                myWriter.println("Fullnames: " + txtNextFirstName.getText() + " " + txtNextSurname.getText());
                myWriter.println("ID Number: " + txtNextCell.getText());
                myWriter.println("Relationship: " + txtNextRelationship.getText());
                myWriter.close();
                JOptionPane.showMessageDialog(new finance(), "Application sent.");

            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
           new welcomePage().setVisible(true);
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(new finance(), "You need a valid license to purchase a car.");
            new welcomePage().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnIDBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDBrowseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtAttachmentID.setText(selectedFile.getAbsolutePath().toString());
        }

    }//GEN-LAST:event_btnIDBrowseActionPerformed

    private void btnPayslipBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayslipBrowseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtAttachmentPayslip.setText(selectedFile.getAbsolutePath().toString());
        }
    }//GEN-LAST:event_btnPayslipBrowseActionPerformed

    private void btnLicneseBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicneseBrowseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtAttachmentLicense.setText(selectedFile.getAbsolutePath().toString());
        }
    }//GEN-LAST:event_btnLicneseBrowseActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnIDBrowse;
    private javax.swing.JButton btnLicneseBrowse;
    private javax.swing.JButton btnPayslipBrowse;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbVehicle;
    private javax.swing.JLabel lblAttachmentID;
    private javax.swing.JLabel lblAttachmentLicense;
    private javax.swing.JLabel lblAttachmentPayslip;
    private javax.swing.JLabel lblCell;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGross;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblNet;
    private javax.swing.JLabel lblNextCell;
    private javax.swing.JLabel lblNextFirstName;
    private javax.swing.JLabel lblNextRelationship;
    private javax.swing.JLabel lblNextSurname;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblVehicle;
    private javax.swing.JLabel lblWork;
    private javax.swing.JPanel pnlAttachements;
    private javax.swing.JPanel pnlNextOfKin;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnYes;
    private javax.swing.JTextField txtAttachmentID;
    private javax.swing.JTextField txtAttachmentLicense;
    private javax.swing.JTextField txtAttachmentPayslip;
    private javax.swing.JTextField txtCell;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGross;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNet;
    private javax.swing.JTextField txtNextCell;
    private javax.swing.JTextField txtNextFirstName;
    private javax.swing.JTextField txtNextRelationship;
    private javax.swing.JTextField txtNextSurname;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtWork;
    // End of variables declaration//GEN-END:variables
}
