/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardealership;

import javax.swing.ImageIcon;

/**
 *
 * @author rjnkr
 */
public class viewCars extends javax.swing.JFrame {


    
    ImageIcon imagePoloVivo = new ImageIcon("poloVivo.png");
    ImageIcon imagePolo = new ImageIcon("polo.png");
    ImageIcon imageTCross= new ImageIcon("tcross.png");
    ImageIcon imageTRoc = new ImageIcon("troc.png");

    
    
    
    /**
     * Creates new form viewCars
     */
    public viewCars() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPreferedCar = new javax.swing.JLabel();
        lblCarIcon = new javax.swing.JLabel();
        cbxCars = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblInstalment = new javax.swing.JLabel();
        lblSellingPrice = new javax.swing.JLabel();
        lblInterestRate = new javax.swing.JLabel();
        lblBaloonPayment = new javax.swing.JLabel();
        lblDeposit = new javax.swing.JLabel();
        lblInstalments = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblInstalmentValue = new javax.swing.JLabel();
        lblSellingPriceValue = new javax.swing.JLabel();
        lblInterestRateValue = new javax.swing.JLabel();
        lblDepositValue = new javax.swing.JLabel();
        lblBaloonPaymentValue = new javax.swing.JLabel();
        lblInstalmentsValue = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(63, 32767));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblPreferedCar.setText("Please choose your preferred car");

        cbxCars.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polo Vivo", "Polo", "T-Cross", "T-Roc" }));
        cbxCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCarsActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblInstalment.setText("Instalment");

        lblSellingPrice.setText("Selling Price");

        lblInterestRate.setText("Interest Rate");

        lblBaloonPayment.setText("Baloon Payment");

        lblDeposit.setText("Deposit");

        lblInstalments.setText("Instalments");

        lblTotal.setText("Total Cost of Credit");

        lblInstalmentValue.setText("jLabel10");

        lblSellingPriceValue.setText("jLabel11");

        lblInterestRateValue.setText("jLabel12");

        lblDepositValue.setText("jLabel13");

        lblBaloonPaymentValue.setText("jLabel14");

        lblInstalmentsValue.setText("jLabel15");

        lblTotalValue.setText("jLabel16");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstalment)
                    .addComponent(lblTotal)
                    .addComponent(lblInstalments)
                    .addComponent(lblDeposit)
                    .addComponent(lblInterestRate)
                    .addComponent(lblSellingPrice)
                    .addComponent(lblBaloonPayment))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalValue)
                    .addComponent(lblInstalmentsValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBaloonPaymentValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDepositValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInterestRateValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSellingPriceValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInstalmentValue, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstalment)
                    .addComponent(lblInstalmentValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSellingPrice)
                    .addComponent(lblSellingPriceValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInterestRate)
                    .addComponent(lblInterestRateValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepositValue)
                    .addComponent(lblDeposit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBaloonPaymentValue)
                    .addComponent(lblBaloonPayment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstalments)
                    .addComponent(lblInstalmentsValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalValue))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreferedCar)
                    .addComponent(lblCarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPreferedCar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblCarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCarsActionPerformed
        
        switch(cbxCars.getSelectedIndex()){
            case 0:
                
                lblCarIcon.setIcon(imagePoloVivo);
                lblInstalmentValue.setText("R3 464");
                lblSellingPriceValue.setText("R 237 400");
                lblInterestRateValue.setText("5.5%");
                lblDepositValue.setText("0%");
                lblBaloonPaymentValue.setText("R 94 960");
                lblInstalmentsValue.setText("72");
                lblTotalValue.setText("R 300 276");
                break;
            case 1:
                lblCarIcon.setIcon(imagePolo);
                lblInstalmentValue.setText("R3 4 4");
                lblSellingPriceValue.setText("R 224 300");
                lblInterestRateValue.setText("7.59%");
                lblDepositValue.setText("0%");
                lblBaloonPaymentValue.setText("R 118 879");
                lblInstalmentsValue.setText("48");
                lblTotalValue.setText("R 282 249");
                break;
            case 2:
                lblCarIcon.setIcon(imageTCross);
                lblInstalmentValue.setText("R4 450");
                lblSellingPriceValue.setText("R 352 300");
                lblInterestRateValue.setText("5.57%");
                lblDepositValue.setText("10.54%");
                lblBaloonPaymentValue.setText("R 183 196");
                lblInstalmentsValue.setText("48");
                lblTotalValue.setText("R 393 796");
                break;
            case 3:
                lblCarIcon.setIcon(imageTRoc);
                lblInstalmentValue.setText("R5 950");
                lblSellingPriceValue.setText("R 494 300");
                lblInterestRateValue.setText("7.59%");
                lblDepositValue.setText("10.49%");
                lblBaloonPaymentValue.setText("R 271 865");
                lblInstalmentsValue.setText("48");
                lblTotalValue.setText("R 557 465");
                break;
            default:
                lblCarIcon.setIcon(imagePoloVivo);
                lblInstalmentValue.setText("R3 464");
                lblSellingPriceValue.setText("R 237 400");
                lblInterestRateValue.setText("5.5%");
                lblDepositValue.setText("0%");
                lblBaloonPaymentValue.setText("R 94 960");
                lblInstalmentsValue.setText("72");
                lblTotalValue.setText("R 300 276");
                break;
        }
        
        
        /*if(cbxCars.getSelectedIndex()== 0){
            lblCarIcon.setIcon(imagePoloVivo);
        }*/
    }//GEN-LAST:event_cbxCarsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        new welcomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblCarIcon.setIcon(imagePoloVivo);
        lblInstalmentValue.setText("R3 464");
        lblSellingPriceValue.setText("R 237 400");
        lblInterestRateValue.setText("5.5%");
        lblDepositValue.setText("0%");
        lblBaloonPaymentValue.setText("R 94 960");
        lblInstalmentsValue.setText("72");
        lblTotalValue.setText("R 300 276");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cbxCars;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBaloonPayment;
    private javax.swing.JLabel lblBaloonPaymentValue;
    private javax.swing.JLabel lblCarIcon;
    private javax.swing.JLabel lblDeposit;
    private javax.swing.JLabel lblDepositValue;
    private javax.swing.JLabel lblInstalment;
    private javax.swing.JLabel lblInstalmentValue;
    private javax.swing.JLabel lblInstalments;
    private javax.swing.JLabel lblInstalmentsValue;
    private javax.swing.JLabel lblInterestRate;
    private javax.swing.JLabel lblInterestRateValue;
    private javax.swing.JLabel lblPreferedCar;
    private javax.swing.JLabel lblSellingPrice;
    private javax.swing.JLabel lblSellingPriceValue;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    // End of variables declaration//GEN-END:variables
}
